// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eagohnnoqimkimkerzqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZ29obm5vcWlta2lta2VyenFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDc0NzYsImV4cCI6MjA2NDA4MzQ3Nn0.WniL83ockz05poO2qljHamTSeH_gBS2PiiuHe5FBlfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);